import com.encima.Message

import com.encima.dwc.DarwinCore

import com.encima.dwc.Occurrence

import com.encima.dwc.Location

import com.encima.dwc.Species

import com.encima.dwc.Identification

import com.encima.utils.DBTools

import com.encima.utils.TimeTools

rule "Time Frame" 
	when dwc:DarwinCore(occ.getEventDate() == "27-MAR-2012")
	then System.out.println(TimeTools.checkAfternoon(dwc.getOcc().getEventTime()));
	end 

rule "Otter River"
	when
		dwc:DarwinCore(DBTools.getLocationDescription(dwc.getOcc().getLocationID()) == "River")
		dwcL:DarwinCore(TimeTools.checkAfternoon(dwcL.getOcc().getEventTime()) == true)
	then
		System.out.println("Otter");
	end
		